{{- if .Values.app.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "city-population.fullname" . }}-es-secrets
  namespace: {{ include "city-population.namespace" . }}
  labels:
    {{- include "city-population.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "city-population.fullname" . }}-es-credentials-kv
      type: Opaque
      data:
        - objectName: es-username
          key: username
        - objectName: es-password
          key: password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: {{ .Values.app.keyVault.userAssignedIdentityClientId | quote }}
    keyvaultName: {{ .Values.app.keyVault.name | quote }}
    tenantId: {{ .Values.app.keyVault.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.app.keyVault.secrets }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
        {{- end }}
{{- end }}
