apiVersion: v1
kind: Service
metadata:
  name: {{ include "city-population.fullname" . }}-api
  labels:
    {{- include "city-population.labels" . | nindent 4 }}
    {{- include "city-population.app.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    {{- include "city-population.app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
